on:
  push:
  workflow_dispatch:
name: CI
jobs:
  free-space:
   runs-on: ubuntu-latest
   steps:
    - name: Increase disk space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:

        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: true
        
        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: false
        swap-storage: true
  flatpak:
    name: 'Flatpak'
    needs: free-space
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-23.08
      options: --privileged
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Restore cache
        id: cache
        uses: actions/cache/restore@v4
        with:
          path: .flatpak-builder
          key: ayugram-flatpak-${{ github.sha }}
          restore-keys: ayugram-flatpak-

      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.3
        with:
          bundle: ayugram.flatpak
          manifest-path: com.ayugram.desktop.yml
          cache: false

      - name: Save cache
        id: cache-save
        uses: actions/cache/save@v4
        if: always()
        with:
          path: .flatpak-builder
          key: ${{ steps.cache.outputs.cache-primary-key }}
